### ISSUE TITLE
Traceback when allowing untrusted issuer

### ISSUE THREAD

**Issue by TheScriptGuy** [TheScriptGuy/certificateChecker#19]
When querying a hostname in a file that has the optional arguments ["local_untrusted_allow"], the following error message appears.

 Traceback (most recent call last):
  File "/projects/github/certificateChecker/certCheck.py", line 401, in <module>
    processQueryFile()
  File "/projects/github/certificateChecker/certCheck.py", line 282, in processQueryFile
    jsonCertificateInfo = o_myCertificate.convertCertificateObject2Json(myHostname["hostname"], myHostname["port"], o_startTime, o_endTime, myCertificate)
  File "/projects/github/certificateChecker/certificate/certificateModule.py", line 357, in convertCertificateObject2Json
    myJsonCertificateInfo["certificateInfo"]["certificateIssuer"] = dict(x[0] for x in __certificateObject["certificateMetaData"]["issuer"])
KeyError: 'issuer'

**Comment by TheScriptGuy** [comment]
The problem is that the webserver being connected to has it's certificates misconfigured.

openssl cannot build the chain to correctly verify it.

Looking at the output of openssl, it looks like it's showing the webserver certificate and root CA certificate but not the intermediate certificates.

We can make some intelligent decisions about how to build the chain based off AIA information.
